config/routes.rb
Prayerthread::Application.routes.draw do
  resources :announcements

  resources :prayers do
    member do
      get :answer
    end
    resources :comments
    resources :intercessions, :only => [:new, :create]
    resources :nudges, :only => [:new, :create]
  end

  resources :activities, :only => :index

  resources :groups do
    resources :memberships
    resources :invitations, :only => [:new, :create, :resend] do
      member do
        put :resend
      end
    end
  end

  match 'help' => 'help#index', :as => :help

  resources :invitations, :only => [:index, :destroy, :accept, :confirm, :ignore] do
    member do
      put :ignore
      get :confirm
      get :accept
    end
  end

  match 'account' => 'users#edit'
  match 'hide_announcements' => 'javascripts#hide_announcements'
  match 'show_announcements' => 'javascripts#show_announcements'

  # Clearance Overrides
  resource :session
  resources :users do
    resource :password, :to => 'clearance/passwords', :only => [:create, :edit, :update]
    resource :confirmation, :to => 'clearance/confirmations', :only => [:new, :create]
  end

  match 'sign_up' => 'users#new', :as => :sign_up
  match 'sign_in' => 'sessions#new', :as => :sign_in
  match 'sign_out' => 'sessions#destroy', :as => :sign_out, :method => :delete
  
  match 'mobile' => 'mobile#force_mobile_view'
  match 'standard' => 'mobile#force_standard_view'
  
  root :to => 'prayers#index'
  # match '/:controller(/:action(/:id))'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  scope :active, lambda { { :conditions => ['starts_at <= ? AND ends_at >= ?', Time.now.utc, Time.now.utc] } }
  scope :since, lambda { |hide_time| { :conditions => (hide_time ? ['updated_at > ? OR starts_at > ?', hide_time.utc, hide_time.utc] : nil) } }

  def self.current_announcements(hide_time)
    active.since(hide_time)
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(@announcement, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(announcements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_box.html.haml
- unless current_announcements.empty?
  #announcements_box
    -for announcement in current_announcements
      %div[announcement]
        = simple_format(announcement.message)
        %p#hide_announcement= link_to "Hide Announcements", hide_announcements_path #, :remote => true

app/views/announcements/_form.html.haml
= form_for @announcement do |f|
  -if @announcement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@announcement.errors.count, "error")} prohibited this announcement from being saved:"
      %ul
        - @announcement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_area :message
  .field
    = f.label :starts_at
    = f.datetime_select :starts_at
  .field
    = f.label :ends_at
    = f.datetime_select :ends_at
  .actions
    = f.submit 'Save'

app/views/announcements/edit.html.haml
%h1 Editing announcement

= render 'form'

= link_to 'Show', @announcement
\|
= link_to 'Back', announcements_path

app/views/announcements/index.html.haml
%h1 Listing announcements

%table
  %tr
    %th Message
    %th Starts at
    %th Ends at
    %th
    %th
    %th

  - @announcements.each do |announcement|
    %tr
      %td= announcement.message
      %td= announcement.starts_at
      %td= announcement.ends_at
      %td= link_to 'Show', announcement
      %td= link_to 'Edit', edit_announcement_path(announcement)
      %td= link_to 'Destroy', announcement, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Announcement', new_announcement_path

app/views/announcements/new.html.haml
%h1 New announcement

= render 'form'

= link_to 'Back', announcements_path

app/views/announcements/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @announcement.message
%p
  %b Starts at:
  = @announcement.starts_at
%p
  %b Ends at:
  = @announcement.ends_at

= link_to 'Edit', edit_announcement_path(@announcement)
\|
= link_to 'Back', announcements_path