config/routes.rb
Prayerthread::Application.routes.draw do
  resources :announcements

  resources :prayers do
    member do
      get :answer
    end
    resources :comments
    resources :intercessions, :only => [:new, :create]
    resources :nudges, :only => [:new, :create]
  end

  resources :activities, :only => :index

  resources :groups do
    resources :memberships
    resources :invitations, :only => [:new, :create, :resend] do
      member do
        put :resend
      end
    end
  end

  match 'help' => 'help#index', :as => :help

  resources :invitations, :only => [:index, :destroy, :accept, :confirm, :ignore] do
    member do
      put :ignore
      get :confirm
      get :accept
    end
  end

  match 'account' => 'users#edit'
  match 'hide_announcements' => 'javascripts#hide_announcements'
  match 'show_announcements' => 'javascripts#show_announcements'

  # Clearance Overrides
  resource :session
  resources :users do
    resource :password, :to => 'clearance/passwords', :only => [:create, :edit, :update]
    resource :confirmation, :to => 'clearance/confirmations', :only => [:new, :create]
  end

  match 'sign_up' => 'users#new', :as => :sign_up
  match 'sign_in' => 'sessions#new', :as => :sign_in
  match 'sign_out' => 'sessions#destroy', :as => :sign_out, :method => :delete
  
  match 'mobile' => 'mobile#force_mobile_view'
  match 'standard' => 'mobile#force_standard_view'
  
  root :to => 'prayers#index'
  # match '/:controller(/:action(/:id))'
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :description, :owner_id
  belongs_to :owner, :class_name => "User"
  has_many :memberships, :dependent => :destroy, :include => :user
  has_many :users, :through => :memberships
  has_many :invitations
  has_and_belongs_to_many :prayers
  
  has_friendly_id :name, :use_slug => true
  
  after_create :ensure_owner_is_a_member
  
  validates_presence_of :name, :owner
  
  protected
  
  def ensure_owner_is_a_member
    memberships.create( :user => self.owner ) if self.owner
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authorize
  load_and_authorize_resource :group

  def show
    set_view
    page_params = params[:print] ? { :page => 1, :per_page => 50 } : { :page => params[:page] }
    @prayers = @group.prayers.view(@view).for_user(current_user).paginate(page_params)

    @intercessions = current_user.intercessions.today.map { |i| i.prayer.id }
    render :layout => (params[:print] ? 'print' : 'application')

  end

  def new
  end

  def create
    @group.owner = current_user
    if @group.save
      flash[:notice] = "Successfully created group."
      redirect_to group_memberships_path(@group)
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update_attributes(params[:group])
      flash[:notice] = "Successfully updated group."
      redirect_to @group
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group.destroy
    flash[:notice] = "Successfully destroyed group."
    redirect_to groups_url
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_command_bar.html.haml
.command_bar
  = link_to "Print this View", group_path( @group, :view => @view.to_s, :detail => @detail, :print => 1 ), :class => 'print', :target => "_blank", :title => "This will launch a print-friendly view with up to 50 prayers."
  %ul
    %li{ :class => ('active' unless show_detail?) }
      = link_to "Summary", group_path( @group, :view => @view, :details => 0 )
    %li{ :class => ('active' if show_detail?) }
      = link_to "Detail", group_path( @group, :view => @view, :details => 1 )
  %ul
    - Prayer::VIEWS.each do |view|
      %li{ :class => ('active' if view == @view) }
        = link_to view.to_s.humanize, group_path( @group, :view => view, :detail => @detail )

app/views/groups/_inputs.html.haml
= form.inputs do
  = form.input :name
  = form.input :description, :as => :text

app/views/groups/_links.html.haml
%ul.links
  %li= link_to "My Prayer List", prayers_path
  = render :partial => "/shared/links"

%h3= h(@group.name)
%ul.links
  %li= link_to "View Members", group_memberships_path(@group)
  %li= link_to "View Prayers", @group
  - if can? :modify, @group
    -# %li= link_to "View Invitations", group_invitations_path(@group)
    %li= link_to "Edit this Group", edit_group_path(@group)

- groups = current_user.groups - [@group]
- unless groups.empty?
  %h3 My Groups
  %ul.links
    - groups.each do |group|
      %li= link_to h(group.name), group

app/views/groups/edit.html.haml
- title "Edit Group"

= semantic_form_for @group do |form|
  = form.error_messages
  = render :partial => "inputs", :locals => { :form => form }
  = form.buttons

%p
  = link_to "Show", group_path(@group)
  |
  = link_to "View All", groups_path
  |
  = link_to "Permanently Delete this Group", @group, :confirm => 'Are you sure?', :method => :delete, :class => 'delete'

app/views/groups/index.html.haml
- title "My Prayer Groups"

= render :partial => "/invitations/pending_message"

- unless @groups.empty?
  .groups
    %table
      - for group in @groups
        %tr
          %td.name
            = link_to h(group.name), group
            .description= h(group.description)
          %td.actions
            %ul.inline
              %li.first= link_to "Prayers", group_path(group)
              %li= link_to "Members", group_memberships_path(group)
              - if can? :edit, group
                %li= link_to "Invite", group_memberships_path(group)
                %li= link_to 'Edit', edit_group_path(group)
- else
  %p 
    You are not a member of any prayers groups.
    %br
    Would you like to
    = link_to "create one now", new_group_path
    ?
%p= link_to "New Group", new_group_path

app/views/groups/new.html.haml
- title "New Group"

= semantic_form_for @group do |form|
  = form.error_messages
  = render :partial => "inputs", :locals => { :form => form }
  = form.buttons

%p= link_to "Back to List", groups_path

app/views/groups/show.html.haml
- title "#{@group.name} : #{prayer_title(@view)}", :subtitle => @group.description

= render :partial => "/invitations/pending_message"

= render :partial => "command_bar"

#prayers
  =render :partial => "/prayers/list"
  
- content_for :sidebar do
  = render :partial => "/groups/links"