config/routes.rb
Prayerthread::Application.routes.draw do
  resources :announcements

  resources :prayers do
    member do
      get :answer
    end
    resources :comments
    resources :intercessions, :only => [:new, :create]
    resources :nudges, :only => [:new, :create]
  end

  resources :activities, :only => :index

  resources :groups do
    resources :memberships
    resources :invitations, :only => [:new, :create, :resend] do
      member do
        put :resend
      end
    end
  end

  match 'help' => 'help#index', :as => :help

  resources :invitations, :only => [:index, :destroy, :accept, :confirm, :ignore] do
    member do
      put :ignore
      get :confirm
      get :accept
    end
  end

  match 'account' => 'users#edit'
  match 'hide_announcements' => 'javascripts#hide_announcements'
  match 'show_announcements' => 'javascripts#show_announcements'

  # Clearance Overrides
  resource :session
  resources :users do
    resource :password, :to => 'clearance/passwords', :only => [:create, :edit, :update]
    resource :confirmation, :to => 'clearance/confirmations', :only => [:new, :create]
  end

  match 'sign_up' => 'users#new', :as => :sign_up
  match 'sign_in' => 'sessions#new', :as => :sign_in
  match 'sign_out' => 'sessions#destroy', :as => :sign_out, :method => :delete
  
  match 'mobile' => 'mobile#force_mobile_view'
  match 'standard' => 'mobile#force_standard_view'
  
  root :to => 'prayers#index'
  # match '/:controller(/:action(/:id))'
end

app/models/invitation.rb
require 'digest/sha1'

class Invitation < ActiveRecord::Base
  attr_accessible :recipient_email
  
  belongs_to :group
  belongs_to :sender, :class_name => "User"
  belongs_to :recipient, :class_name => "User"
  
  validates_presence_of :group
  validates_presence_of :recipient_email, :on => :create, :message => "can't be blank"
  validates_format_of :recipient_email, 
    :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i,
    :message => "is not a valid email format, e.g. john@company.com"
  validate :membership_does_not_exist, 
    :pending_invitation_does_not_exists, 
    :on => :create
  
  before_save :initialize_invitation_token
  
  scope :pending, includes(:group).where(:accepted_at => nil, :ignored => false).order("sent_at DESC")
  scope :pending_and_ignored, where(:accepted_at => nil)
  
  after_create :send_invitation_email, :unless => :accepted?
  
  def accepted?
    !accepted_at.nil?
  end
  
  def accept!(user)
    unless accepted?
      update_attribute( :accepted_at, Time.now )
      Membership.create( :group => self.group, :user => user )
    end
  end
  
  def send_invitation_email
    InvitationMailer.invite(self).deliver
    update_attribute :sent_at, Time.now
  end
  
  protected
  
    def membership_does_not_exist
      existing_user = User.find_by_email(recipient_email)
      if existing_user && Membership.exists?( :group_id => group, :user_id => existing_user )
        errors.add("recipient_email", "is already a member of this group")
      end
    end
    
    def pending_invitation_does_not_exists
      if Invitation.exists?( :group_id => group, :recipient_email => recipient_email, :accepted_at => nil )
        errors.add("recipient_email", "already has a pending invitation to this group")
      end
    end

    def generate_invitation_token
      self.token = Digest::SHA1.hexdigest("--#{Time.now.utc}--#{recipient_email}--")
    end

    def initialize_invitation_token
      generate_invitation_token if new_record?
    end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :authorize, :except => :confirm
  before_filter :load_group, :only => [:new, :create, :resend]
  before_filter :forbid_missing_token, :only => [:confirm]

  def index
    @invitations = current_user.invitations.pending_and_ignored
    @sent_invitations = current_user.sent_invitations.pending
  end

  def new
    @invitation = Invitation.new
  end

  # Invitations are created in the memberships controller
  #
  # def create
  #   @invitation = @group.invitations.build(params[:invitation])
  #   @invitation.sender = current_user
  #   if @invitation.save
  #     flash[:notice] = "Successfully sent invitation for #{@invitation.recipient_email}."
  #     redirect_to group_memberships_path(@group)
  #   else
  #     render :action => 'new'
  #   end
  # end

  def destroy
    @invitation = Invitation.find(params[:id])
    if can? :destroy, @invitation
      @invitation.destroy
      flash[:notice] = "Successfully deleted invitation."
    else
      flash[:error] = "Sorry, only the group owner or recipient can delete an invitation"
    end
    redirect_to invitations_path
  end

  def confirm
    @invitation = Invitation.pending.find_by_id_and_token(params[:id], params[:token])
    if @invitation
      @user = current_user || User.find_by_email(@invitation.recipient_email)
      if @user
        @user.invitations << @invitation
        @user.save!
        flash[:notice] = "Please sign in to accept your invitation." if signed_out?
        redirect_to invitations_path
      else
        redirect_to sign_up_path( :token => params[:token] )
      end
    else
      flash[:error] = "Unable to find a valid invitation."
      redirect_to root_path
    end
  end

  def accept
    @invitation = Invitation.pending.find_by_id_and_token(params[:id], params[:token])
    if @invitation
      @invitation.accept!(current_user)
      flash[:notice] = "You have successfully joined the '#{@invitation.group.name}' group."
      redirect_to @invitation.group
    else
      flash[:error] = "Unable to find a matching invitation"
      redirect_to root_path
    end
  end

  def ignore
    begin
      @invitation = current_user.invitations.find(params[:id])
      @invitation.update_attribute :ignored, true
      flash[:notice] = "That invitation won't bother you anymore."
    rescue ActiveRecord::RecordNotFound => ex
      flash[:error] = "Unable to find a matching invitation"
    end
    redirect_to invitations_path
  end

  def resend
    @invitation = @group.invitations.find(params[:id])
    if @invitation && can?( :create, @invitation )
      @invitation.send_invitation_email
      flash[:notice] = "Your invitation has been resent to #{@invitation.recipient_email}."
    else
      flash[:error] = "Sorry, you can't resend an invitation."
    end
    redirect_to group_memberships_path(@group)
  end

  private

  def load_group
    @group = Group.find(params[:group_id])
  end

  def forbid_missing_token
    if params[:token].blank?
      raise ActionController::Forbidden, "missing token"
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  
  def format_related_users_for_autocomplete(group)
    # Related users that are not in the the current group
    logger.debug "Loading related users"
    related = User.related(current_user, *group.users)
    related.map! { |u| "'#{u.first_name} #{u.last_name} (#{u.email})'" }
    "var related_users = [ #{related.join(', ')} ];"
  end
  
end

app/views/invitations/_list.html.haml
%table
  %tr
    %th Sent By
    %th Group
    %th Sent
    %th
  - for invitation in invitations
    %tr
      %td= h invitation.sender.name
      %td= h invitation.group.name
      %td
        = "#{time_ago_in_words(invitation.sent_at)} ago"
        - if invitation.ignored?
          (ignored)
      %td.actions
        %ul.inline
          %li.first= link_to 'Accept', accept_invitation_path(invitation, :token => invitation.token)
          - if invitation.ignored?
            %li= link_to 'Delete', invitation, :method => :delete, |
              :confirm => 'This will permanently delete this invitation. Are you sure?' |
          - else
            %li= link_to 'Ignore', ignore_invitation_path(invitation), :method => :put

app/views/invitations/_new.html.haml
#add_member_area.box

  = semantic_form_for @invitation, :url => group_memberships_path(@group), :method => :post do |form|
    = form.inputs do
      = form.input :recipient_email, :label => "Add New Member", :hint => "Enter the email address of the person to invite."
      -# = form.input :role, :collection => Membership.role_options, :selected => Membership.default_role, :include_blank => false
    = form.buttons do
      = form.commit_button "Add Member"

%script{ :type => "text/javascript" }
  = format_related_users_for_autocomplete( @group )

app/views/invitations/_notice.html.haml
.box
  %h2 Your invitation is waiting...
  %p
    You've been invited by
    %strong= @invitation.sender.name
    to join the prayer group 
    %strong= @invitation.group.name
    %span>.
  %p
    %strong
      If you already have an account, please 
      = link_to( "sign in", accept_invitation_path(@invitation, :token => params[:token]))
      to accept the invitation.

app/views/invitations/_pending.html.haml
- show_group ||= false
- unless invitations.empty?
  %h3 Pending Invitations
  #pendinginvitations
    %table
      %tr
        %th Email
        - if show_group
          %th Group
        %th Sent
        %th 
      - invitations.each do |invitation|
        %tr
          %td.email= h invitation.recipient_email
          - if show_group
            %th= link_to h(invitation.group.name), group_memberships_path(invitation.group)
          %td.sent
            = time_ago_in_words(invitation.sent_at || invitation.created_at)
            ago
          %td.actions
            %ul.inline
              %li.first= link_to "Resend", resend_group_invitation_path(invitation.group, invitation), :method => :put
              %li= link_to "Delete", invitation_path(invitation), |
                :method => :delete, |
                :confirm => "Are you want to cancel the invitation sent to #{h invitation.recipient_email}?", |
                :class => 'delete' |

app/views/invitations/_pending_message.html.haml
- count_pending = current_user.invitations.pending.count
-if count_pending > 0
  .box
    %strong= "You have #{pluralize(count_pending, 'pending invitation')}."
    #{link_to "Click here to review and accept", invitations_path}.

app/views/invitations/confirm.html.haml
Congrats! You've been invited.

= signed_in?

= debug @invitation

= render :partial => "/invitations/notice"

app/views/invitations/index.html.haml
- title "Invitations"

  
%h3 Invitations Waiting for Your Acceptance
- unless @invitations.empty?
  = render :partial => "list", :locals => { :invitations => @invitations }
-else
  .box
    %strong You currently have no pending invitations.
    %p 
      You may want to 
      = link_to "create your own group", new_group_path
      and invite other's to join.

- unless @sent_invitations.empty?
  = render :partial => "pending", :locals => { :invitations => @sent_invitations, :show_group => true }
    
%p= link_to raw("&laquo; Back to your prayer list"), prayers_path

app/views/invitations/new.html.haml
- title "Invite to #{@group.name}"

%p Enter the email address of the person you wish to invite to this group.

= semantic_form_for [@group, @invitation] do |form|
  = form.error_messages
  = form.inputs do
    = form.input :recipient_email, :hint => "Something such as 'john@company.com'"
  = form.buttons do
    = form.commit_button "Invite"

%p= link_to "Back to the group", @group

%script{ :type => "text/javascript" }
  = format_related_users_for_autocomplete( @group )