config/routes.rb
Prayerthread::Application.routes.draw do
  resources :announcements

  resources :prayers do
    member do
      get :answer
    end
    resources :comments
    resources :intercessions, :only => [:new, :create]
    resources :nudges, :only => [:new, :create]
  end

  resources :activities, :only => :index

  resources :groups do
    resources :memberships
    resources :invitations, :only => [:new, :create, :resend] do
      member do
        put :resend
      end
    end
  end

  match 'help' => 'help#index', :as => :help

  resources :invitations, :only => [:index, :destroy, :accept, :confirm, :ignore] do
    member do
      put :ignore
      get :confirm
      get :accept
    end
  end

  match 'account' => 'users#edit'
  match 'hide_announcements' => 'javascripts#hide_announcements'
  match 'show_announcements' => 'javascripts#show_announcements'

  # Clearance Overrides
  resource :session
  resources :users do
    resource :password, :to => 'clearance/passwords', :only => [:create, :edit, :update]
    resource :confirmation, :to => 'clearance/confirmations', :only => [:new, :create]
  end

  match 'sign_up' => 'users#new', :as => :sign_up
  match 'sign_in' => 'sessions#new', :as => :sign_in
  match 'sign_out' => 'sessions#destroy', :as => :sign_out, :method => :delete
  
  match 'mobile' => 'mobile#force_mobile_view'
  match 'standard' => 'mobile#force_standard_view'
  
  root :to => 'prayers#index'
  # match '/:controller(/:action(/:id))'
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, opts = {})
    options = { :show => true, :subtitle => nil }.merge(opts)
    content_for(:title) { page_title.to_s }
    @show_title = options[:show]
    if options[:subtitle]
      content_for(:subtitle) { options[:subtitle].to_s }
      @show_subtitle = options[:show]
    end
  end
  
  def show_title?
    @show_title
  end

  def show_subtitle?
    @show_subtitle
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  def body(opts = {})
    @body_class = opts[:class]
    @body_id = opts[:id]
  end
end

app/views/layouts/_context.html.haml
- if signed_in?
  %ul.inline
    %li.first
      = image_tag raw(current_user.gravatar_url( :size => 20 )), :alt => current_user.first_name
      ="Welcome #{current_user.first_name}!"
    %li
      = link_to "Invites", invitations_path
      = link_to(current_user.invitations.pending.count, invitations_path, :class => 'pending_invitation_count')
    %li= link_to "My Account", account_path
    %li= link_to "Help", help_path
    %li= link_to "Sign Out", sign_out_path
- else
  = link_to "Sign Up", sign_up_path
  or
  = link_to "Sign In", sign_in_path

app/views/layouts/_feedback.html.haml
%h3 Feedback
Do you have questions, comments, or feature requests? Head over to our
= link_to "support forum", "http://groups.google.com/group/prayerthread", :target => "_blank"
and let us know.

app/views/layouts/_menu.html.haml
%ul.inline
  %li.first= link_to "Recent Activity", activities_path
  %li= link_to "Prayer List", prayers_path
  %li= link_to "My Groups", groups_path

app/views/layouts/application.html.haml
!!! Strict
%html{html_attrs}
  %head
    %title
      = "PrayerThread :: #{yield(:title)}"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = csrf_meta_tag
    = stylesheet_link_tag 'compiled/screen', :media => "screen, projection"
    = stylesheet_link_tag 'compiled/print', :media => "print"
    /[if lt IE 8]
      = stylesheet_link_tag 'compiled/ie', :media => "screen, projection"
    = javascript_include_tag :defaults, :cache => true
    = javascript_include_tag "http://cdn.jquerytools.org/1.2.3/tiny/jquery.tools.min.js"
    = yield(:head)
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-3709570-6']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  %body
    #container
      #header
        #context
          = render :partial => "/layouts/context"
        #title= link_to raw("prayer<span class=\"alt\">thread</span>"), root_path
        - if signed_in?
          #menu
            = render :partial => "/layouts/menu"

        - if show_title?
          %h1
            = yield(:title)
            - if show_subtitle?
              .subtitle= yield(:subtitle)
              
      = render 'announcements/box'

      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}", :class => name

      #content
        = yield

      #sidebar
        = yield(:sidebar)
        
        %h3 Want to help?
        %p{ :style => "text-align:center;"}= render "shared/paypal"
        %p
          This project is a labor of love and is solely supported by donation from 
          PrayerThread users. If you find this tool useful, please consider 
          helping out. 
        %p
          No amount is too small to help offset development &amp; server costs 
          (or a date night with my wife).
        %p Thanks so much, 
        %p -Ryan
        
      #footer
        - if is_mobile_device?
          .mobile_switch
            On a mobile device?
            = link_to "Switch to the mobile site.", mobile_path
        Copyright &copy;2010 
        = link_to "sourcescape.com", "http://sourcescape.com", :target => "_blank"
        &bull;
        We're interested in your feedback! 
        = mail_to "prayerthread@googlegroups.com", "Drop us a note"
        and let us know what you think.
    
    - if Rails.env.production?
      = render :partial => "shared/uservoice"

app/views/layouts/application.mobile.haml
!!! Mobile
%html{html_attrs}
  %head
    %title= "PrayerThread :: #{h(yield(:title))}"
    %meta{ :name => "viewport", :content => "width=device-width" }
    = stylesheet_link_tag 'compiled/mobile'
    = javascript_include_tag 'jquery-1.4.2.min', 'rails.js', 'mobile.js'
    -# 
      = stylesheet_link_tag 'iui/iui.css'
      = javascript_include_tag 'iui/iui.js', :cache => true
  %body{ :id => @body_id, :class => @body_class }
    #header
      -# menu
        %ul.inline
          %li.first= link_to "prayers", prayers_path
          %li= link_to "groups", groups_path
      prayer
      %span> thread
    .container
      - if show_title?
        %h1
          =h yield(:title)
      .inner
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}", :class => name
        = yield
    #footer
      %span.mobile_switch= link_to "Switch to the standard site", standard_path
      - if signed_in?
        |
        = link_to "Sign out", sign_out_path

app/views/layouts/notification_mailer.html.erb
<table style="margin: 5px">
  <tr>
    <td id="header">
      <div id="header" style="border-bottom: 1px solid #A8B1B8; font-size: 1.2em; letter-spacing: 0.8em; margin: 0.5em 0px; padding-bottom: 0.5em;">
        <a href="http://prayerthread.org/" style="text-decoration: none; color: #6d98ab;">prayer<span class="alt" style="color: #00275E; font-weight: bold;">thread</span></a>
      </div>
    </td>
  </tr>
  <tr>
    <td id="content">
      <p>Hi <%= @recipient.first_name %>,</p>
      <%= yield %>
    </td>
  </tr>
  <tr>
    <td id="footer">
      <p style="border-top: 1px solid #A8B1B8; font-size: 0.9em; color: #666; margin: 1em 0; padding-top: 1em;">
        This message sent from PrayerThread.<br />
        <%= link_to "Have feedback or suggestions? Let us know.", "http://prayerthread.uservoice.com", :style => "color: #00275e;" %><br />
        <%= link_to "Manage your email preferences.", account_url, :style => "color: #00275e;" %><br /><br />
        Prayer Thread: <%= link_to "www.prayerthread.org", "http://www.prayerthread.org", :style => "color: #00275e;" %><br />
        - DO NOT REPLY TO THIS EMAIL -
      </p>
    </td>
  </tr>
</table>

app/views/layouts/notification_mailer.text.erb
Hi <%= @recipient.first_name %>,

<%= yield %>

--------------------------------------------------------------------------------------------------
This message sent from PrayerThread.
Manage your email preferences at http://www.prayerthread.org/account

Prayer Thread: www.prayerthread.org
- DO NOT REPLY TO THIS EMAIL -

app/views/layouts/print.html.haml
!!! Strict
%html{html_attrs}
  %head
    %title
      = "PrayerThread :: #{h(yield(:title))}"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag 'compiled/print', :media => "screen, projection, print"
    /[if lt IE 8]
      = stylesheet_link_tag 'compiled/ie', :media => "screen, projection"
    = javascript_include_tag :defaults, :cache => true
    = yield(:head)
  %body
    #container
      #header
        #title= link_to raw("prayer<span class=\"alt\">thread</span>"), root_path
        - if show_title?
          %h1
            =h yield(:title)
            - if show_subtitle?
              .subtitle=h yield(:subtitle)
      #content
        = yield
      #footer 
        Copyright &copy;2010 
        = link_to "sourcescape.com", "http://sourcescape.com", :target => "_blank"
        &bull;
        We're interested in your feedback! 
        = mail_to "prayerthread@googlegroups.com", "Drop us a note"
        and let us know what you think.